//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePlace.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExternalService()
        {
            this.ReleaseExternalServices = new HashSet<ReleaseExternalService>();
        }
    
        public System.Guid ExternalServiceID { get; set; }
        public string Name { get; set; }
        public string Region { get; set; }
        public string StageEndPoint { get; set; }
        public string StageComment { get; set; }
        public string ProdEndPoint { get; set; }
        public string ProdComment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReleaseExternalService> ReleaseExternalServices { get; set; }
    }
}
