//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePlace.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OnePlaceEntities : DbContext
    {
        public OnePlaceEntities()
            : base("name=OnePlaceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ExternalService> ExternalServices { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ReleaseDate> ReleaseDates { get; set; }
        public virtual DbSet<Release> Releases { get; set; }
        public virtual DbSet<PorjectLangauge> PorjectLangauges { get; set; }
        public virtual DbSet<ReleaseChangeSet> ReleaseChangeSets { get; set; }
        public virtual DbSet<ReleaseExternalService> ReleaseExternalServices { get; set; }
        public virtual DbSet<ReleaseSitecorePackage> ReleaseSitecorePackages { get; set; }
        public virtual DbSet<ReleaseTFSFilePath> ReleaseTFSFilePaths { get; set; }
        public virtual DbSet<Status> Status { get; set; }
    
        public virtual ObjectResult<GetReleaseDetails_Result> GetReleaseDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReleaseDetails_Result>("GetReleaseDetails");
        }
    
        public virtual ObjectResult<GetReleaseList_Result> GetReleaseList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReleaseList_Result>("GetReleaseList");
        }
    }
}
