//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePlace.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public System.Guid ProjectID { get; set; }
        public string Name { get; set; }
        public string Region { get; set; }
        public string DPMID { get; set; }
        public string StagePreviewURL { get; set; }
        public string StageCDURL { get; set; }
        public string ProdPreviewURL { get; set; }
        public string ProdCDURL { get; set; }
        public Nullable<System.Guid> DefaultLanguageID { get; set; }
        public Nullable<bool> IsMultilingual { get; set; }
        public string Comment { get; set; }
    }
}
