//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePlace.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReleaseDate
    {
        public System.Guid ReleaseID { get; set; }
        public string DateType { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public string Status { get; set; }
    
        public virtual Release Release { get; set; }
    }
}
